python train_gemma.py \
  --model_name_or_path unsloth/gemma-3-4b-it \
  --load_in_8bit \
  --max_seq_length 2048 \
  --do_train \
  --do_eval \
  --train_file "Data/hf_data.json" \
  --num_slices 4 \
  --lora_r 8 \
  --lora_alpha 8 \
  --per_device_train_batch_size 4 \
  --gradient_accumulation_steps 2 \
  --learning_rate 2e-5 \
  --max_steps 2000 \
  --evaluation_strategy steps \
  --eval_steps 10 \
  --logging_steps 10 \
  --save_steps 10 \
  --output_dir "output_gemma3/" \
  --logging_dir "output_gemma3/" \
  --seed 42
